<a href="https://colab.research.google.com/github/Juxtpawan/Data-Science/blob/main/operationnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating an array of cars
import numpy as np
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
#accessing the second car from the array
cars[1]


'buick skylark 320'

In [ ]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing second car - 0 represents 1st row and 1 represents 2nd element of the row
car_hp_arr[0,1]


'buick skylark 320'

In [ ]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing name of last car using negative indexing
car_hp_arr[0,-1]



'ford torino'

In [ ]:
#creating an array of cars
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
#accessing a subset of cars from the array
cars[1:4]


array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [ ]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name and horsepower
car_hp_acc_arr[0:2]


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [ ]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name and horsepower of last two cars
car_hp_acc_arr[0:2, 3:5]


array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U25')

In [ ]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name, horsepower and acceleration of first three cars
car_hp_acc_arr[0:3, 0:3]


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U25')

In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#mean horsepower
print("Mean horsepower = ",np.mean(horsepower_arr))


Mean horsepower =  147.0


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#median horsepower
print("Median horsepower = ",np.median(horsepower_arr))


Median horsepower =  150.0


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))

Minimum horsepower:  130
Maximum horsepower:  165


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.argmin(horsepower_arr))
print("Maximum horsepower: ", np.argmax(horsepower_arr))

Minimum horsepower:  0
Maximum horsepower:  1


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x) # gives the indices
# With the indices , we can find those values
horsepower_arr[x]

(array([1, 2, 3]),)


array([165, 150, 150])

In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#creating filter array
filter_arr = horsepower_arr >150
newarr = horsepower_arr [filter_arr]
print(filter_arr)
print(newarr)

[False  True False False False]
[165]


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)

original array:  [130 165 150 150 140]
Sorted array:  [130 140 150 150 165]
original array after sorting:  [130 165 150 150 140]


In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)


original array:  [130 165 150 150 140]
Sorted array:  [130 140 150 150 165]
original array after sorting:  [130 165 150 150 140]


In [ ]:
# sum of number using vectorization
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))
# addition of extra mark
additional_marks = [2, 2, 5, 10, 1]
student_marks_arr += additional_marks
print(student_marks_arr)
# above operation can be perform as
student_marks_arr = np.add(student_marks_arr, additional_marks)
student_marks_arr

359
[80 94 41 74 90]


array([82, 96, 46, 84, 91])

In [ ]:
import numpy as np
# Array 1
array1=np.array([5, 10, 15])
# Array 2
array2=np.array([5])
array3= array1 / array2
array3


array([1., 2., 3.])

In [ ]:
#Students marks in 4 subjects
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
print(students_marks)
additional_marks =np.array([5,10])
students_marks = np.add(students_marks ,additional_marks)
students_marks

[[67 45]
 [90 92]
 [66 72]
 [32 40]]


array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])